### ISSUE TITLE
Please add an english version

### ISSUE THREAD

**Issue by Cads182** [DrAbcrealone/EzAsWeapon#1]
Please!, this program has a lot of potential!

**Comment by DrAbcOfficial** [comment]
To be honest, I've almost given up this project.
This project started with horrible structure and unbearable coding, which mean it's hard to add any new features or find and fix any bugs unless re-coding it.
Anyway, updated, and you can find new version in release.
To change language, just click "关于"→"语言"→"English" in menu strips.

**Comment by Cads182** [comment]
Thanks a lot!
